CREATE TABLE IF NOT EXISTS weather (
    id SERIAL NOT NULL PRIMARY KEY,
    city TEXT NOT NULL,
    temp FLOAT NOT NULL ,
    condition TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);